// Code generated by goctl. DO NOT EDIT.
// Source: contact.proto

package server

import (
	"context"

	"tikstart/rpc/contact/contact"
	"tikstart/rpc/contact/internal/logic"
	"tikstart/rpc/contact/internal/svc"
)

type ContactServer struct {
	svcCtx *svc.ServiceContext
	contact.UnimplementedContactServer
}

func NewContactServer(svcCtx *svc.ServiceContext) *ContactServer {
	return &ContactServer{
		svcCtx: svcCtx,
	}
}

func (s *ContactServer) CreateMessage(ctx context.Context, in *contact.CreateMessageRequest) (*contact.Empty, error) {
	l := logic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}

func (s *ContactServer) GetLatestMessage(ctx context.Context, in *contact.GetLatestMessageRequest) (*contact.GetLatestMessageResponse, error) {
	l := logic.NewGetLatestMessageLogic(ctx, s.svcCtx)
	return l.GetLatestMessage(in)
}

func (s *ContactServer) GetMessageList(ctx context.Context, in *contact.GetMessageListRequest) (*contact.GetMessageListResponse, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}
